### ISSUE TITLE
Propostas de paletras - Meetup Floripa #7

### ISSUE THREAD

**Issue by rgazeredo** [react-brasil/awesome-react-events-br#12]
# 7º Encontro - ReactJS Florianópolis
### Local
[Segware](http://www.segware.com.br/)
**Rua Nirberto Haase, 60 - Edifício Santa Mônica Office - Santa Monica, Florianópolis - SC**
### Data e hora
**24/02/2018 - 13:15 até 16:15**

### [MeetUp](http://meetu.ps/e/DPS82/5r8yl/f)
http://meetu.ps/e/DPS82/5r8yl/f

Envie sua proposta comentando neste Issue!

## Sugestão de template:
**Título da palestra:**

**Público alvo**
Iniciante | Intermediário | Avançado

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**

## Markdown:
```
**Título da palestra:**

**Público alvo:**

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**
```

**Comment by andreyluiz** [comment]
**Título da palestra:**
Quando devo utilizar o estado do React?

**Público alvo:**
Intermediário

**Nome do Palestrante:**
Andrey Luiz

**Resumo da palestra:**
Em aplicações de larga escala, é comum necessitar de bibliotecas como o Redux, para trabalhar juntamente com o React na obtenção de dados de API, do localstorage e etc. Porém, algumas vezes, as pessoas usam o estado do Redux como estado para todas as coisas, inclusive recursos de interface. Por exemplo, spinners de carregamento, mensagens de erro e etc. Mas será que isso deve mesmo ficar no Redux? Será o React não cuidaria melhor disso? É o que pretendo mostrar e discutir com a galera.

**Material (Se houver):**
Ainda não tenho.

**Comment by rgazeredo** [comment]
**Título da palestra:**
Como o code review pode fazer bem para sua equipe

**Público alvo:**
Iniciante

**Nome do Palestrante:**
Vinícius Alonso

**Resumo da palestra:**
Como o code review pode fazer bem para sua equipe

**Comment by geovannikun** [comment]
**Título da palestra:**
Mobx: Uma alternativa ao Redux

**Público alvo:**
Iniciante/Intermediário

**Nome do Palestrante:**
Geovanni Pacheco

**Resumo da palestra:**
Apresentar o Mobx na teoria e pratica

**Material (Se houver):**
Ainda não tenho.

**Comment by geovannikun** [comment]
**Título da palestra:**
React Native com Expo

**Público alvo:**
Iniciante

**Nome do Palestrante:**
Geovanni Pacheco

**Resumo da palestra:**
Apresentar o React Native e as facilidades da ferramenta/framework Expo para desenvolvimento nativo.

**Material (Se houver):**
Ainda não tenho.

**Comment by rafaelmotta** [comment]
Título da palestra:
O que aprendi usando React Native nos últimos 2 anos e o que esperar para o próximo ano

Público alvo:
Iniciante

Nome do Palestrante:
Rafael

Resumo da palestra:
Apresentar vantagens e desvantagens do React Native e o que esperar dessa tecnologia para o futuro.

Material (Se houver):
Ainda não tenho.

**Comment by andreyluiz** [comment]
**Título da palestra:**
Tirando proveito dos _lifecycle methods_ do React

**Público alvo:**
Iniciante/Intermediário

**Nome do Palestrante:**
Andrey Luiz

**Resumo da palestra:**
É possível fazer coisas muito legais com React. Mas para otimizar a renderização, e exibir a coisa certa no momento certo, os _lifecycle methods_ podem beneficiar muito a criação do componente.

**Material (Se houver):**
Nope.

**Comment by arojunior** [comment]
**Sugestão de Cronograma 1**

13:15 - Abertura do evento
13:40 - Talk 1 (30 min)
14:10 - Intervalo 30 min
14:50 - Talk 2  (30 min)
15:20 - Intevalo 40min - Coffee break
16:00 - Talk 3  (30 min)
16:30 - Intervalo 20 min
16:50 - Talk 4  (30 min)
17:20 - Encerramento do evento / Discussão sobre melhorias
18:00 - #partiu

**Comment by andreyluiz** [comment]
Galera, já podiam organizar quais talks vão ser encaixadas, pois sábado já está aí.

**Comment by arojunior** [comment]
**Sugestão de Cronograma 2**

13:15 - Abertura do evento
13:40 - Talk 1 (30 min)
14:10 - Intervalo 40 min
14:50 - Talk 2  (30 min)
15:20 - Intevalo 40min - Coffee break
16:00 - Talk 3  (30 min)
16:30 - Intervalo 40 min
17:10 - Encerramento do evento / Discussão sobre melhorias
17:40 - #partiu

**Comment by geovannikun** [comment]
Não seria legal colocar uma roda de conversa igual rola em outros eventos?

**Comment by arojunior** [comment]
**Cronograma**

13:15 - Abertura do evento
13:40 - Talk 1 - Como o code review pode fazer bem para sua equipe. Vinicius Alonso (30 min)
14:10 - Perguntas  (10 min)
14:20 - Intervalo 30 min
14:50 - Talk 2 - Quando devo utilizar o estado do React? Andrey Luiz (30 min)
15:20 - Perguntas (10 min)
15:30 - Intervalo 40min - Coffee break
16:10 - Talk 3 - Mobx: Uma alternativa ao Redux. Geovanni Pacheco (30 min)
16:40 - Perguntas (10 min)
16:50 - Intervalo 20 min
17:10 - Talk 4 - O que aprendi usando React Native nos últimos 2 anos e o que esperar para o próximo ano. Rafael Motta (30 min)
17:40 - Perguntas (10 min)
17:50 - Encerramento do evento / Discussão sobre melhorias
