### ISSUE TITLE
Propostas de paletras - Meetup Floripa #8

### ISSUE THREAD

**Issue by rgazeredo** [react-brasil/awesome-react-events-br#15]
# 8º Encontro - ReactJS Florianópolis
### Local
[Softplan](https://www.softplan.com.br/)
**Av. Luiz Boiteux Piazza, 1302 - Cachoeira do Bom Jesus, 88030-912 · Florianópolis**
### Data e hora
**28/04/2018 - 13:30 até 18:00**

### [MeetUp](https://www.meetup.com/pt-BR/ReactJS-Floripa/events/249739406/)
https://www.meetup.com/pt-BR/ReactJS-Floripa/events/249739406/

Envie sua proposta comentando neste Issue!

## Sugestão de template:
**Título da palestra:**

**Público alvo**
Iniciante | Intermediário | Avançado

**Tempo previsto**
(entre 15min à 60min)

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**

## Markdown:
```
**Título da palestra:**

**Público alvo:**

**Tempo previsto:**

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**
```

**Comment by jaburcodes** [comment]
**Título da palestra:**
Deep dive into Animated API

**Público alvo:**
Intermediário | Avançado

**Nome do Palestrante:**
Guilherme Jabur

**Resumo da palestra:**
Se você já fez ou viu alguma animação feita em um aplicativo construído com React Native tenho certeza que em 95% dos casos ela foi feita com Animated API.

Na talk vamos mergulhar fundo nos entendimentos dessa API fornecida pelo react-native e realmente entender oque está acontecendo quando a utilizamos.

**Comment by rafaelmotta** [comment]
**Título da palestra:**
Repensando suas aplicações com React

**Público alvo:**
Intermediário | Avançado

**Tempo previsto:**
50 min

**Nome do Palestrante:**
Rafael Michels Motta

**Resumo da palestra:**
Essa palestra visa mostrar algumas novas features que foram introduzidas ao longo da v16, como o novo algoritmo interno (Fiber), Portals, Fragments, Error Boundaries, Context API e os novos lifecycle methods (e descontinuação de alguns deles).

**Comment by sebas5384** [comment]
**Título da palestra:**
Unleash the power of HTML5 Canvas with React Konva

**Público alvo:**
Intermediário | Avançado

**Tempo previsto:**
40 min

**Nome do Palestrante:**
Sebastian Ferrari ( @sebas5384 )

**Resumo da palestra:**
Vou falar sobre como usar React para controlar Canvas do HTML5 e o que aprendi após ter feito um GraphQL Schema Designer (WIP) baseado no [Neo4J Browser](https://neo4j.com/developer/guide-neo4j-browser/) e [Juju Gui](https://jujucharms.com/docs/2.3/controllers-gui#monitoring) utilizando [React Konva](https://github.com/lavrton/react-konva).

**Material:**
Video (old): https://www.youtube.com/watch?v=srPB3c8bz3o
Repo: https://github.com/sebas5384/graphql-explorer

**Comment by MarcoNicolodi** [comment]
**Título da palestra:**
A pirâmide de testes na prática com React + Redux, Jest, Enzyme e Cypress

**Público alvo:**
Intermediário 

**Tempo previsto:**
50 min

**Nome do Palestrante:**
Marco Nicolodi

**Resumo da palestra:**
Você provavelmente já viu a famosa piramide de testes, que mostra relação de velocidade/custo/quantidade entre unit/integration/e2e tests. Mas muita gente não sabe a diferença entre unit e integration testes. Mais gente ainda não faz integration tests. Outra parte, deixa a parte e2e apenas para o QA. Nesta palestra vou mostrar na prática o que são cada um dos testes, demonstrando através de um container redux simples. Terá live coding de cada tipo de teste.


**Material (Se houver):**
Em breve
