### ISSUE TITLE
Propostas de palestras - Meetup Floripa #9

### ISSUE THREAD

**Issue by arojunior** [react-brasil/awesome-react-events-br#17]
# 9º Encontro - ReactJS Florianópolis
### Local
[Resultados Digitais](https://resultadosdigitais.com.br/)
**Rodovia Vírgilio Várzea, S/N - Floripa Office anexo ao Floripa Shopping**
### Data e hora
**16/06/2018 - 14:00 até 18:30**

[Meetup.com/ReactJS-Floripa](https://www.meetup.com/ReactJS-Floripa/events/251280437)

Envie sua proposta comentando neste Issue!

## Sugestão de template:
**Título da palestra:**

**Público alvo**
Iniciante | Intermediário | Avançado

**Tempo previsto**
(entre 15min à 60min)

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**

## Markdown:
```
**Título da palestra:**

**Público alvo:**

**Tempo previsto:**

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**
```

**Comment by arojunior** [comment]
@rafaelmotta Será que rola aquela talk nessa edição?

**Comment by jaburcodes** [comment]
**Título da palestra:**
New Context API

**Público alvo:**
Iniciantes  / Intermediário

**Tempo previsto:**
20 minutos

**Nome do Palestrante:**
Guilherme Jabur

**Resumo da palestra:**
Oque é a context API, como usá-la e oque exatamente ela resolve?

**Material (Se houver):**
Ainda não tenho, mas abri uma PR a respeito disso em um projeto open source a pouco tempo, para quem se interessar: https://github.com/react-brasil/reactconfbr-app/commit/57e195ec66e555a612398bcf9a9ecb3f85e54600

**Comment by dleitee** [comment]
**Título da palestra:**
React Fetches a new way to make requests into your REST API's.

**Público alvo:**
Todos

**Tempo previsto:**
30 min

**Nome do Palestrante:**
Daniel Leite de Oliveira

**Resumo da palestra:**
Será apresentada a minha nova lib react-fetches e qual o motivo da criação, também vou apresentar um roadmap para que os interessados possam ajudar a contribuir.

Vai rolar live coding.

**Material (Se houver):**
[https://github.com/dleitee/react-fetches](https://github.com/dleitee/react-fetches)
[https://github.com/dleitee/fetches](https://github.com/dleitee/fetches)

**Comment by pedronauck** [comment]
**Título da palestra:** Anunciando Docz ✍🏻 Uma lib simples que vai ajudar você a documentar e criar seus components! 

**Público alvo:** Intermediário

**Tempo previsto:** 30m

**Nome do Palestrante:** Pedro Nauck

**Resumo da palestra:** Live coding mostrando um pouco sobre como o Docz funciona, principais conigurações, como criar custom templates e um pouco do que rola por trás com Socket.IO, MDX e AST parsing! #sentaquelávemcódigo 🙌🏻

**Material (Se houver):** https://github.com/pedronauck/docz

**Comment by nicholasess** [comment]
***Título da palestra***: Mercado de Trabalho com ReactJs

***Público alvo***: Iniciante/Intermediario

***Tempo previsto***: 25m

***Nome do Palestrante***: Nicholas Eduardo

***Resumo da palestra***: Explicar o mercado e os pilares de um dev para conseguir emprego na área

***Material***: https://docs.google.com/presentation/d/1etyjRFhPgThuvuUHJvXBY2-35DW740BnAo2ZLhTdCzo/edit?usp=sharing

**Comment by jaburcodes** [comment]
Valeeeeeu galera, baita evento, só talk top!!
