### ISSUE TITLE
Propostas de palestras - Meetup Floripa  + Facebook Developers Circle

### ISSUE THREAD

**Issue by arojunior** [react-brasil/awesome-react-events-br#18]
# 10º Encontro - ReactJS Florianópolis + Facebook Developers Circle
### Local
A definir
### Data e hora
**28/07/2018 - 14:00 até 18:30**

[Meetup.com/ReactJS-Floripa](https://www.meetup.com/ReactJS-Floripa/events/252407670/)

[Grupo Facebook Developers Circle Florianópolis](https://www.facebook.com/groups/169510177066827/)

Envie sua proposta comentando neste Issue!

## Sugestão de template:
**Título da palestra:**

**Público alvo**
Iniciante | Intermediário | Avançado

**Tempo previsto**
(entre 15min à 60min)

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**

## Markdown:
```
**Título da palestra:**

**Público alvo:**

**Tempo previsto:**

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**
```

**Comment by lucianomlima** [comment]
A ideia é listar os grupos que promovem eventos ou os eventos em si?
Porque ao ter o link do grupo, automaticamente tem acesso aos eventos que ocorreram ou virão a ocorrer não?

**Comment by LeandroMattosUXe** [comment]
Título da palestra: Performance em UX: quantificando a subjetividade com métricas biológicas e cognitivas/emocionais

Público alvo: Iniciante

Tempo previsto
(entre 30min a 60min)

Nome do Palestrante: Leandro Mattos 
https://www.linkedin.com/in/professorleandromattos/ 
https://www.linkedin.com/company/ux-human-behavior/ 

Resumo da palestra:
- Como nos sentimos diante do paradoxo da escolha
- Como reagimos diante de uma boa experiência
- O que sentimos diante de uma boa usabilidade
- Rastreamento ocular (Eye Tracker) aplicado à UX
- Pupilometria aplicada (Eye Tracker) à UX
- Identificação de emoções via expressões faciais (Face Reader), aplicadas à UX
- Eletroencefalografia (EEG) aplicada à UX
- Análise da atividade eletrodérmica (EDA) aplicada à UX
- Aumento da performance em UX via novos indicadores de desempenho

Material: 
Serão disponibilizados os slides trabalhados na apresentação
Laboratório completo de neurociência aplicada ao consumo, com o qual apresentaremos de forma prática, com interação do público, cases próprios sobre aumento de performance em user experience.

**Comment by arojunior** [comment]
**Título da palestra:**
What about Next.js?

**Público alvo**
Iniciante

**Tempo previsto**
Ainda não terminei o material, mas não deve passar de 30min

**Nome do Palestrante:**
Junior Oliveira

**Resumo da palestra:**
Overview sobre o framework Next.Js, exemplo de código e deploy

**Material (Se houver):**
https://github.com/arojunior/what-about-nextjs
