### ISSUE TITLE
Formato mais Abrangente

### ISSUE THREAD

**Issue by lucianomlima** [react-brasil/awesome-react-events-br#20]
Podemos trabalhar com mais endereços relacionados aos eventos de react.

Algo tipo:

### UF
 - GroupName - Location | [Site](https://www.site.com) - [Facebook](https://facebook.com) - [Twitter](https://www.twitter.com)

Quem tiver todos, adiciona todos. Quem não tiver, por exemplo concentra tudo no Facebook, pode colocar somente o Facebook.

**Comment by gabrielferreiraa** [comment]
@lucianomlima estou fechando a issue pelo fato do tempo dela estar aqui, e pelo fato da lista atual já estar bastante parecida com a proposta! Qualquer coisa pode abrir novamente, abraço!
