### ISSUE TITLE
11º Encontro - ReactJS Florianópolis

### ISSUE THREAD

**Issue by arojunior** [react-brasil/awesome-react-events-br#23]
# 11º Encontro - ReactJS Florianópolis
### Local
[Exact Sales](https://exactsales.com.br/)
**Rod. José Carlos Daux, 600 - João Paulo, Florianópolis - SC, 88030-000 (ParqTec Alfa)**
### Data e hora
**22/09/2018 - 14:00 até 18:00**

[Meetup.com/ReactJS-Floripa](https://www.meetup.com/ReactJS-Floripa/events/254567792/)

Envie sua proposta comentando neste Issue!

## Sugestão de template:
**Título da palestra:**

**Público alvo**
Iniciante | Intermediário | Avançado

**Tempo previsto**
(entre 15min à 60min)

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**

## Markdown:
```
**Título da palestra:**

**Público alvo:**

**Tempo previsto:**

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**
```

**Comment by felpin** [comment]
**Título da palestra:** Why soft skills matter

**Público alvo:** Todos

**Tempo previsto:** ~30 minutos

**Nome do Palestrante:** Felipe Pinheiro

**Resumo da palestra:** Será abordada a importância de soft skills para os desenvolvedores e algumas dicas para aprimorá-las

**Comment by haskellcamargo** [comment]
**Título da palestra:** O peso da faculdade na carreira de um programador

**Público alvo:**

- Pessoas que pretendem seguir para a área
- Estão iniciando ou demasiadamente preocupadas com possuir uma graduação
- Preocupam-se em não conseguir crescer sem diploma

**Tempo previsto:** 30 minutos

**Nome do Palestrante:** Celão

**Resumo da palestra:**
Quero abordar sobre o quão importante (será?) seria a conclusão da graduação em uma área em constante crescimento. O objetivo não é gerar polêmica, mas mostrar que faculdade em TI já não serve mais como garantia de emprego, e entrar um pouco no assunto de como as pessoas tem diferentes maneiras de aprender - e isso não é errado.
Quero dar uma introdução de como comecei na área acidentalmente (na qual estou há 6 anos) e quebrar alguns mitos sobre requisitos de empresas.

**Comment by nicholasess** [comment]
Título da palestra: O que a comunicação mudou na minha carreira

Público alvo: Todos

Tempo previsto: ~30 minutos

Nome do Palestrante: Nicholas Eduardo

Resumo da palestra: Vou falar sobre os benefícios que obtive, dos erros e acertos que aconteceram na minha vida. Quero mostrar o outro lado da moeda e o que impacta quando você se torna comunicativo.

**Comment by nicholasess** [comment]
**Título da palestra**: Os robôs vão me substituir ou me contratar?

**Público alvo**: Todos

**Tempo previsto**: ~30 minutos

**Nome do Palestrante**: Marcelo Benez

**Resumo da palestra**: Vou falar um pouco do que está sendo/será mais valorizado no profissional de engenharia de software e o que é tendência.
