### ISSUE TITLE
Propostas de palestra - 14º Encontro - ReactJS Floripa

### ISSUE THREAD

**Issue by sebas5384** [react-brasil/awesome-react-events-br#26]
# 14º Encontro - ReactJS Florianópolis

[Meetup.com/ReactJS-Floripa](https://www.meetup.com/ReactJS-Floripa/events/260886872/)

Envie sua proposta comentando neste Issue!

## Sugestão de template:
**Título da palestra:**

**Público alvo**
Iniciante | Intermediário | Avançado

**Tempo previsto**
(entre 15min à 50min)

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**

## Markdown:
```
**Título da palestra:**

**Público alvo:**

**Tempo previsto:**

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**
```

**Comment by tavioalves** [comment]
**Título da palestra: Como React me tornou um desenvolvedor JavaScript melhor?**

**Público alvo: Junior e Pleno **

**Tempo previsto: 20 minutos **

**Nome do Palestrante: Otavio Augusto **

**Resumo da palestra: Resumir e apresentar como boas práticas que o React trás consigo, me ajudaram com a evoluir/aprender os fundamentos de JavaScript/ES6. Tópicos como imutabilidade, programação funcional, Class e "this",  Higher-Order Functions, ES6 bultin functions e mais. **

**Comment by sebas5384** [comment]
**Título da palestra:** 
De um sistema legado para microsserviços com GraphQL

**Público alvo:**
Intermediário | Avançado

**Tempo previsto:**
25 minutos

**Nome do Palestrante:**
Sebastian Ferrari https://www.linkedin.com/in/sebas5384/

**Resumo da palestra:**
Vou mostrar como o GraphQL, um protocolo e query language tipado, com documentação automática, tolerante a falhas e um ecossistema rico em ferramentas pode ser um aliado fundamental na migração de seu legado para microsserviços.

**Material (Se houver):**
https://docs.google.com/presentation/d/1-pZBtAP0NpBdfK3A-u9HRr5To5aUVYc74K_FKhs9eBM/edit?usp=sharing
