### ISSUE TITLE
Meetup Florianópolis - Nº 4

### ISSUE THREAD

**Issue by sebas5384** [react-brasil/awesome-react-events-br#3]
**Data do meetup:** 29/04/2017

Galera! como pediram seguem as propostas de palestras que foram enviadas pelo [formulário](https://docs.google.com/forms/d/e/1FAIpQLSfYwj7PBjIBZr_QlEmEGXdqyv8JIUsHzNZBNP530Li5EIuhQA/viewform) para a votação de vocês.

Votem utilizando a reação 👍 

**Encerramento:** Quarta-feira 22:30h 26/04/2017

[MODELO]
```
**Título**

**Público alvo**

**Resumo**

**Material**

**Autor**
```

**Comment by sebas5384** [comment]
**Título**
Desenvolva a sua aplicação React em uma linguagem expressiva e 100% funcional
**Público alvo**
Iniciante
**Resumo**
Comparar uma implementação TodoMVC feita em React puro com outra em ClojureScript.
**Autor**
Sam (Alisson Nunes)

**Comment by sebas5384** [comment]
**Título**
React Native: Tudo o que você precisa saber.
**Público alvo**
Iniciante
**Resumo**
Abordar sobre essa tecnologia,  como ela funciona, vantagens, desvantagens e comparações com outras bibliotecas do genêro.
**Material**
https://www.youtube.com/watch?v=lpyWut0bNF8
**Autor**
Rafael Motta

**Comment by sebas5384** [comment]
**Título**
Growth Hacker
**Público alvo**
Avançado
**Resumo**
Relay + GraphQL
**Material**
https://www.liveedu.tv/brunoguerra/
**Autor**
Bruno Guerra ([Twitter](https://twitter.com/megabga))

**Comment by sebas5384** [comment]
**Título**
React Native + Electron?
**Público alvo**
Iniciante
**Resumo**
Como fazer uma aplicação em react-native rodar no Electron e o porque.
**Autor**
Rafael Fuzifaru Cianci | [Twitter](https://twitter.com/rafacianci)

**Comment by sebas5384** [comment]
**Título**
Hands-on com React Native, um Waze da Feira Livre
**Público alvo**
Iniciante
**Resumo**
Nessa palestra iremos usar React Native para criar, em 30min, um app colaborativo para compartilhar preços de frutas e verduras. Nosso app irá listar os produtos vendidos nas Centrais de Abastecimento(CEASA), que são locais onde vendem as frutas e verduras que vão para os supermercados, restaurantes e chegam nas nossas mesas. Com a cotação dos produtos em mãos, compradores poderão barganhar melhor com os vendedores e economizarão na hora das compras.
**Autor**
Felipe de Araujo | [Twitter](https://twitter.com/felipedaraujo_)

**Comment by sebas5384** [comment]
**Título**
What the Flux?! Let's Redux
**Público alvo**
Iniciante
**Resumo**
Apresentar ferramentas que facilitam a integração entre React e Redux, como react-redux, redux-actions, redux-form e redux-promise.
**Material**
https://github.com/arojunior/what-the-flux-lets-redux
Slides ainda em produção: https://docs.google.com/presentation/d/1z0qeJv0QcAc_Dp9kuv0miEnKdy22boRp8JuHLmPJ_3c/edit?usp=sharing"
**Autor**
Júnior Oliveira | [Twitter](https://twitter.com/arojunior)

**Comment by sebas5384** [comment]
**Título**
React Native: Hands on
**Público alvo**
Iniciante
**Resumo**
Abordar de maneira prática e fácil como iniciar com react native, criando seu primeiro componente para mobile, diferença entre plataformas, testes, dificuldades e etc.
**Autor**
Rafael Michels Motta

**Comment by felipedaraujo** [comment]
@sebas5384, se puder adicionar o link para o material da minha apresentação, aqui está https://github.com/felipedaraujo/ceasaonline-react-native Muito obrigado! :shipit: :neckbeard:

**Comment by sebas5384** [comment]
@felipedaraujo done!

**Comment by sebas5384** [comment]
Pessoal, obrigado pelas votações! 👍 

Seguem as palestras selecionadas, lembrando que temos que considerar a **distribuição de tópicos**, para não ter duas palestras com o mesmo assunto.

**Desenvolva a sua aplicação React em uma linguagem expressiva e 100% funcional.**
_Sam (Alisson Nunes)_

**Hands-on com React Native, um Waze da Feira Livre.**
_Felipe de Araujo_

**What the Flux?! Let's Redux.**
_Júnior Oliveira_

Entrarei em contato com cada autor para confirmar sua participação.

Ahhh!! a palestra "React Native: Tudo o que você precisa saber" do Rafael Michels Motta, fica agendada pro próximo! 👍

**Comment by sebas5384** [comment]
Pessoal consegui confirmar as palestras:
**Hands-on com React Native, um Waze da Feira Livre.**
Felipe de Araujo

**What the Flux?! Let's Redux.**
Júnior Oliveira

mas não a do Sam (Alisson Nunes), ele não me respondeu, então o que vocês acham da palestra "Growth Hacker" do _Bruno Guerra_ ?

**Comment by sebas5384** [comment]
Todas as palestras confirmadas pessoal!! \o/
