### ISSUE TITLE
Submissão de Talks - 17º React Floripa

### ISSUE THREAD

**Issue by welitonderesende** [react-brasil/awesome-react-events-br#31]
# 14º Encontro - ReactJS Florianópolis
### Meetup.com/ReactJS-Floripa

Envie sua proposta comentando neste Issue!

**Sugestão de template:**
### Público alvo
*Iniciante | Intermediário | Avançado*

### Tempo previsto
*(entre 15min à 50min)*

### Material (Se houver):

Markdown:
```
**Título da palestra:**

**Público alvo:**

**Tempo previsto:**

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**
```

**Comment by andrelmlins** [comment]
**Título da palestra:**
Desenvolvendo bibliotecas para React.

**Público alvo:**
Iniciante/Intermediário

**Tempo previsto:**
25/30min

**Nome do Palestrante:**
André Lins

**Resumo da palestra:**
No dia a dia utilizamos várias bibliotecas para React ou Javascript com o objetivo de facilitar nosso trabalho. Bibliotecas de componentes, datas, rotas, gerenciamento de estados, entre outras, são comuns na criação de aplicações. Mas você já parou para pensar em tudo que necessita para criar bibliotecas? Quais são as dificuldades, desafios e quais artefatos são necessários para criação dessas bibliotecas? Nessa talk iremos falar sobre todo esse processo, mostrando as ferramentas necessárias e bibliotecas que facilitarão o desenvolvimento da sua primeira biblioteca para React.

**Comment by rthomazel** [comment]
**Título da palestra:**
Tipos Em Javascript Hoje

**Público alvo:**
Avançado 

**Tempo previsto:**
20/25m

**Nome do Palestrante:**
Raphael "Tom" Thomazella

**Resumo da palestra:**
- retrospectiva rápida sobre o JS como linguagem e seu ecossistema 
- discussão sobre coerção de tipos, operadores e sintaxe do js, do ponto de vista dos tipos.
- discussão sobre uso de tipos em js, do ponto de vista do problema.
- ferramentas de tipagem que temos hoje
- discussão panorâmica sobre o design da linguagem e suas implicações, tc39, comparação com outras linguagens dinâmicas e compiladas.
- discussão panorâmica sobre metodologia de desenvolvimento de software, TDD, e nas implicações de escolher tipar seu js ou não tipar.

**Material (Se houver):**

(Pendente)

**Comment by thiagocordeirooo** [comment]
**Título da palestra:**
Extensões VScode: Construindo extensão para nos auxiliar na produtividade.

**Público alvo:**
Desenvolvedores

**Tempo previsto:**
15m

**Nome do Palestrante:**
Thiago Cordeiro

**Resumo da palestra:**
Vou mostrar o quão simples é criar uma extensão para o VScode, que pode nos ajudar muito no dia-a-dia.

**Material (Se houver):**
Hands-on, mostrar o código fonte da extensão [Generate Translation](https://marketplace.visualstudio.com/items?itemName=thiagocordeirooo.generate-translation) e os principais desafios enfrentados.
