### ISSUE TITLE
Submissão de Talks - 19º React Floripa

### ISSUE THREAD

**Issue by itsweliton** [react-brasil/awesome-react-events-br#32]
19º Encontro - ReactJS Florianópolis
[Meetup.com/ReactJS-Floripa](https://www.meetup.com/ReactJS-Floripa/)
Envie sua proposta comentando neste Issue!

### Público alvo
_(Iniciante | Intermediário | Avançado)_

### Tempo previsto
_(entre 15min à 50min)_

### Material _(Se houver)_

```
Markdown:

**Título da palestra:**

**Público alvo:**

**Tempo previsto:**

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**
```

**Comment by renanmav** [comment]
**Título da palestra:**

Deploy serverless de aplicações React (SPA e SSR)

**Público alvo:**

Entre intermediário e avançado

**Tempo previsto:**

20~40 min

**Nome do Palestrante:**

João Marins @jgcmarins 

**Resumo da palestra:**

Dentre as diversas skills que um frontend deve ter, talvez fazer deploy não seja a mais importante e alguns irão falar que isso é trabalho do devOps, mas em um mundo em que ser fullstack é praticamente inerente, não faz mal aprender como fazer deploy da página que você está codando, seja ela SPA ou SSR. 

PS: é importante que tenha internet durante a talk pois pretendo fazer demos

**Comment by wevtimoteo** [comment]
**Título da palestra:**

Qualidade de código além de ESLint

**Público alvo:**

Iniciante em diante

**Tempo previsto:**

30 min

**Nome do Palestrante:**

Weverton Timoteo

**Resumo da palestra:**

Já faz um tempo que ferramentas de Integração Contínua e CI-como-serviço se tornaram um requisito para qualquer projeto que queira alguma garantia que as funcionalidades existentes funcionam ou que um bug foi devidamente corrigido. Configurar qualquer uma dessas ferramentas é rápido e fácil, então verificar cada commit/pull request/merge request acabou sendo crucial na tarefa de ajudar times à ficar de olho na suite de testes.

Mas será que é suficiente só verificar se o build está verde para saber que a sua entrega tem qualidade? Além de packages, algumas "métricas-como-serviços" vêm surgindo, se propondo a monitorar a "qualidade" do software, não confiando apenas em testes automatizados.

Mas como se define qualidade? O que torna um código "bom"?

Devemos apenas medir a cobertura de testes e rodar ferramentas de análise estática ou sintática?

Quais métricas são mais importantes para medir a qualidade de código do projeto que você trabalha? E como analisar a nossa base de código JavaScript com ou sem ReactJS?

Nessa talk irei cobrir algumas métricas agnósticas à linguagem de programação como tipos de Cobertura, Complexidade e Acoplamento e um tour por algumas regras utilizadas para melhorar nosso código ES6.

**Comment by thiagocordeirooo** [comment]
**Título da palestra:**
Extensões VScode: Construindo extensão para nos auxiliar na produtividade.

**Público alvo:**
Desenvolvedores

**Tempo previsto:**
20~30m

**Nome do Palestrante:**
Thiago Cordeiro

**Resumo da palestra:**
Vou mostrar o quão simples é criar uma extensão para o VScode, que pode nos ajudar muito no dia-a-dia.

**Material (Se houver):**
Hands-on, mostrar o código fonte da extensão Generate Translation e os principais desafios enfrentados.
