### ISSUE TITLE
19º Encontro - React Floripa - Online

### ISSUE THREAD

**Issue by itsweliton** [react-brasil/awesome-react-events-br#34]
# 19º Encontro - ReactJS Florianópolis
Meetup.com/ReactJS-Floripa
Envie sua proposta comentando neste Issue!

Sugestão de template:

## Título da palestra:
Público alvo
Iniciante | Intermediário | Avançado

## Tempo previsto
(entre 15min à 50min)

## Markdown:

```
**Título da palestra:**

**Público alvo:**

**Tempo previsto:**

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**

```

**Comment by LauraBeatris** [comment]
**Título da palestra:** Os mitos sobre useMemo e useCallback

**Público alvo:** Intermediário

**Tempo previsto:** 50min

**Nome do Palestrante:** Laura Beatris 

**Resumo da palestra:** Vamos conversar sobre os custos e beneficios de utilizar ``useMemo`` e ``useCallback``. Performance possui um tradeoff e nem sempre vem com beneficios. Muitas equipes acabam utilizando esses hooks em todo component, de maneira desnecessaria e resultando no efeito contrario.

**Comment by itsweliton** [comment]
Confirmado Laura :D até semana que vem!
