### ISSUE TITLE
Talk: Os mitos sobre useMemo e useCallback

### ISSUE THREAD

**Issue by LauraBeatris** [react-brasil/awesome-react-events-br#35]
**Título da palestra:** Os mitos sobre useMemo e useCallback

**Público alvo:** Intermediário

**Tempo previsto:** 50min

**Nome do Palestrante:** Laura Beatris 

**Resumo da palestra:** Vamos conversar sobre os custos e beneficios de utilizar ``useMemo`` e ``useCallback``. Performance possui um tradeoff e nem sempre vem com beneficios. Muitas equipes acabam utilizando esses hooks em todo component, de maneira desnecessaria e resultando no efeito contrario.

**Comment by sibelius** [comment]
temos o link?

**Comment by tavareshenrique** [comment]
Quando vai ser, por favor?

**Comment by devmozao** [comment]
Interessado no tema. No aguardo de uma data ou link, caso já tenha acontecido.

**Comment by matheus1lva** [comment]
muito interessado no tema!

**Comment by Ridermansb** [comment]
Link.. data do evento... ? :) tb estou interessado.

**Comment by LauraBeatris** [comment]
Sorry guys... 

A tempestade que acontenceu aqui em SC acabou levando meu cérebro junto. 

Isso é a proposta de um talk para o meetup do ReactJS Floripa #34  

Vou fechar essa issue e colocar a proposta lá
