### ISSUE TITLE
20º Encontro - React Floripa - Online

### ISSUE THREAD

**Issue by itsweliton** [react-brasil/awesome-react-events-br#37]
20º Encontro - ReactJS Florianópolis
Meetup.com/ReactJS-Floripa
Envie sua proposta comentando neste Issue!

Sugestão de template:

## Título da palestra:
Público alvo
Iniciante | Intermediário | Avançado

## Tempo previsto
(entre 15min à 50min)

## Markdown:

```
**Título da palestra:**

**Público alvo:**

**Tempo previsto:**

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**
```

**Comment by welitonderesende** [comment]
#close
