### ISSUE TITLE
Retro do Meetup de React Floripa Nº 4

### ISSUE THREAD

**Issue by arojunior** [react-brasil/awesome-react-events-br#4]
**Coisas a manter:**
1. Talks sobre assuntos como apresentação de empresa, ou vagas.

**Coisas a melhorar:**
1. Primeira palestra pra nivel inicial.
2. Pre requisitos explícitos com indicação de material de estudo.
3. Aumentar o tempo de networking entre as palestras. **A definir.**
4. Deixar o tempo de palestra livre com mínimo de 15 minutos e um maximo de 40 de minutos.
5. Informações pos palestras, com links e material.

**Comment by ronal2do** [comment]
Bom dia, @arojunior vc está se referindo ao MeetUp São Paulo de React em sua quarta edição? Ou em um contexto geral? De qualquer forma vamos considerar a sugestão e obrigado.

**Comment by sebas5384** [comment]
@ronal2do desculpa cara, eu que escrevi isso pelo computador do @arojunior, e esqueci de colocar que era o meetup de Floripa.

Isso é a retrospectiva do meetup que rolou no sábado passado.
