### ISSUE TITLE
Assuntos de interesse para o 5º Meetup ReactJS Florianópolis

### ISSUE THREAD

**Issue by fnmunhoz** [react-brasil/awesome-react-events-br#5]
Olá pessoal!

O 5º encontro já está marcado para o dia 10/06/17 e gostaríamos de sugestões de temas.

Vou colocar alguns que podem ser votados utilizando a reação 👍 .

Fiquem a vontade para adicionar novos temas, que também podem ser votados.

**Comment by fnmunhoz** [comment]
CSS in JS

**Comment by sebas5384** [comment]
Testes com Jest

**Comment by sebas5384** [comment]
Redux

**Comment by gneutzling** [comment]
React Router 4

**Comment by felipedaraujo** [comment]
React Fiber

**Comment by arojunior** [comment]
Recompose

**Comment by sebas5384** [comment]
Case de sucesso

**Comment by sebas5384** [comment]
[React Konva](https://github.com/lavrton/react-konva)
React + Canvas = Love. JavaScript library for drawing complex canvas graphics using React.

**Comment by mauscoelho** [comment]
[redux-observable](https://redux-observable.js.org/)
Redux + RxJs
