### ISSUE TITLE
Propostas de palestras para votação - Meetup Florianópolis - Nº 5

### ISSUE THREAD

**Issue by sebas5384** [react-brasil/awesome-react-events-br#6]
**Data do meetup:** 10/06/2017

Seguem as propostas de palestras que foram enviadas pelo [formulário](https://docs.google.com/forms/d/e/1FAIpQLSfYwj7PBjIBZr_QlEmEGXdqyv8JIUsHzNZBNP530Li5EIuhQA/viewform) para a votação de vocês.

Votem utilizando a reação 👍 

**Encerramento:** Domingo 23:30h 04/06/2017

Aguardem!! as palestras serão colocadas aqui assim que forem enviadas para nós.

**Comment by mauscoelho** [comment]
**Título**
React para Iniciantes

**Público alvo**
Iniciante

**Resumo**
Se você é ligado nas novidades do mundo JavaScript, já ouviu falar de React mas nunca teve tempo para entender como funciona, esta é a sua oportunidade para enteder o básicos e iniciar seu primeiro projeto!

Serão abordados os seguintes tópicos

- Nomenclatura
- O que são componentes
- Como definir componentes
- Ciclo de vida de componentes
- Sistema de eventos
- Linguagem de marcacao JSX
- Tooling: Babel e Webpack
- Live Coding: Botando pra funcionar


**Material**
http://www.slideshare.net/derekstavis/react-for-beginners

**Comment by mauscoelho** [comment]
**Título**
Live Code React + CSS Modules

**Público alvo**
Iniciante

**Resumo**
Será uma demonstração de como o React e CSS Modules funcionam juntos e como algumas questões de reaproveitamento podem ser abordadas

**Material**
http://blog.taller.net.br/introducao-ao-css-modules/

**Comment by mauscoelho** [comment]
**Título**
From upside down to right side up: A journey in React.

**Público alvo**
Intermediário

**Palestrante**
Pedro Nauck

**Resumo**
Pretendo mostrar algumas dicas/ferramentas/boas práticas de como manter o environment de uma aplicação React consistente, modular e como fugir de práticas que poderiam comprometer sua aplicação.

**Comment by mauscoelho** [comment]
**Título**
Growth Hacker

**Público alvo**
Avançado

**Palestrante**
Bruno Guerra @megabga

**Resumo**
Relay + GraphQL

**Material**
https://www.liveedu.tv/brunoguerra/

**Comment by mauscoelho** [comment]
**Título**
React Native + Electron?

**Público alvo**
Iniciante

**Palestrante**
Rafael Fuzifaru Cianci @rafacianci

**Resumo**
Como fazer uma aplicação em react-native rodar no Electron e o porque.

**Comment by mauscoelho** [comment]
**Título**
React Native: Hands on

**Público alvo**
Iniciante

**Palestrante**
Rafael Michels Motta

**Resumo**
Abordar de maneira prática e fácil como iniciar com react native, criando seu primeiro componente para mobile, diferença entre plataformas, testes, dificuldades e etc.
