### ISSUE TITLE
Propostas de paletras - Meetup Floripa #6

### ISSUE THREAD

**Issue by fnmunhoz** [react-brasil/awesome-react-events-br#9]
Envie sua proposta comentando neste Issue!

## Sugestão de template:

**Título da palestra:**

**Público alvo**
Iniciante | Intermediário | Avançado

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**

## Markdown:
```
**Título da palestra:**

**Público alvo:**

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**
```

**Comment by dleitee** [comment]
**Título da palestra:** 
Promessa é dívida, uma história baseada em fatos reais.

**Público alvo:**
Iniciante / Intermediário

**Nome do Palestrante:**
Daniel Leite de Oliveira

**Resumo da palestra:**
Você já teve problemas com `promises` usando `redux`? 

Nessa palestra vou mostrar a maneira como lidamos com requests em nossas aplicações e como isso melhorou a performance do nosso time.

**Comment by vieiralucas** [comment]
**Título da palestra:**
React error boundaries

**Público alvo:**
Iniciante | Intermediário

**Nome do Palestrante:**
Lucas Vieira

**Resumo da palestra:** 
Um erro de JavaScript numa parte da interface não deveria quebrar toda a aplicação. Para resolver este problema, React 16 introduz um novo conceito "error boundary".

**Material (Se houver):**
https://facebook.github.io/react/blog/2017/07/26/error-handling-in-react-16.html

**Comment by lucasfcosta** [comment]
**Título da palestra:**
VDom from the transpiler to the browser

**Público alvo:**
Intermediário

**Nome do Palestrante:**
Lucas Fernandes da Costa

**Resumo da palestra:**
Como diria o físico Richard Feynman:

> What I cannot create I do not understand.

Vamos explorar como funciona o JSX desde o compilador até o renderer e o browser. Falando sobre como o Babel transforma seu JSX e lida com seus arquivos de código e os algoritmos utilizados para criar componentes, mantê-los atualizados, removê-los e interagir com o DOM em geral.

Ainda nas palavras do mestre Feynman:

> Know how to solve every problem that has been solved

**Material (Se houver):**
https://medium.com/@rajaraodv/the-inner-workings-of-virtual-dom-666ee7ad47cf
